repos:
  - repo: local
    hooks:
      - id: testing
        name: testing
        description: This hook tests the app
        entry: ./bin/test.sh
        language: python
        types: [text]
      - id: bumping-version
        name: Bumping version
        description: This hook bumps the version of the app
        entry: uv run ./bin/bump-version.py
        language: python
        types: [text]

default_stages: [pre-push]
