---
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Installe Build Tools
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest
